---

- name: Set root password
  command: vzctl set 1001 --userpasswd root:{{vlead_user_password}}

- name: copy interface ifcfg-eth0 file
  template: src=ifcfg-eth0 dest=/vz/private/1001/etc/sysconfig/network-scripts/
  
- name: copy interface ifcfg-eth1 file
  template: src=ifcfg-eth1 dest=/vz/private/1001/etc/sysconfig/network-scripts/

- name: Router's Network restart
  command: vzctl exec 1001 service network restart

- name: Set iptable rule 
  command: vzctl exec 1001 iptables -t nat -A POSTROUTING ! -d {{subnet}} -o eth0 -j SNAT --to-source {{ipaddress.router}}

- name: iptables Saving 
  command: vzctl exec 1001 iptables-save > /etc/sysconfig/iptables

- name: ipv4 forwarding in router
  replace:
     path: /vz/private/1001/etc/sysctl.conf
     regexp: 'net.ipv4.ip_forward = 0'
     replace: 'net.ipv4.ip_forward = 1'

- name: reboot
  command: vzctl restart 1001
  register: out
- debug: var=out.stdout_lines

