---
 - name: Copy ssh keys
   shell: sshpass -p "{{vlead_user_password}}" ssh-copy-id root@localhost
   register: out
 - debug: var=out.stdout_lines
 
 - name: Copy ssh keys
   shell: sshpass -p "{{vlead_user_password}}" ssh-copy-id root@127.0.0.1
   register: out
 - debug: var=out.stdout_lines

 - name: Copy ssh keys
   shell: sshpass -p "{{vlead_user_password}}" ssh-copy-id root@10.100.1.1
   register: out
 - debug: var=out.stdout_lines

 - name: Copy ssh keys
   shell: sshpass -p "{{vlead_user_password}}" ssh-copy-id root@10.100.1.2
   register: out
 - debug: var=out.stdout_lines
 
 - name: Copy ssh keys
   shell: sshpass -p "{{vlead_user_password}}" ssh-copy-id root@10.100.1.3
   register: out
 - debug: var=out.stdout_lines
 
 - name: Copy ssh keys
   shell: sshpass -p "{{vlead_user_password}}" ssh-copy-id root@10.100.1.4
   register: out
 - debug: var=out.stdout_lines

 - name: Copy ssh keys
   shell: sshpass -p "{{vlead_user_password}}" ssh-copy-id root@10.100.1.5
   register: out
 - debug: var=out.stdout_lines
 
 - name: Copy ssh keys
   shell: sshpass -p "{{vlead_user_password}}" ssh-copy-id root@10.100.1.6
   register: out
 - debug: var=out.stdout_lines

 - name: Copy ssh keys
   shell: sshpass -p "{{vlead_user_password}}" ssh-copy-id root@10.100.1.7
   register: out
 - debug: var=out.stdout_lines

 - name: Copy ssh keys
   shell: sshpass -p "{{vlead_user_password}}" ssh-copy-id root@10.100.1.8
   register: out
 - debug: var=out.stdout_lines

 - name: Copy ssh keys
   shell: sshpass -p "{{vlead_user_password}}" ssh-copy-id root@10.100.1.9
   register: out
 - debug: var=out.stdout_lines

 - name: Copy ssh keys
   shell: sshpass -p "{{vlead_user_password}}" ssh-copy-id root@10.100.1.10
   register: out
 - debug: var=out.stdout_lines

