---
- name: Commenting rsnapshot_client 
  lineinfile: 
     path: systems-model/build/{{clustername}}/public_dns.yaml
     regexp: '^    - rsnapshot_client'
     line: '    # - rsnapshot_client'
  

- name: Commenting ossec_client 
  lineinfile: 
     path: systems-model/build/{{clustername}}/public_dns.yaml
     regexp: '^    - ossec_client'
     line: '    # - ossec_client'

- name: Commenting rsnapshot_client 
  lineinfile: 
     path: systems-model/build/{{clustername}}/private_dns.yaml
     regexp: '^    - rsnapshot_client'
     line: '    # - rsnapshot_client'
  

- name: Commenting ossec_client 
  lineinfile: 
     path: systems-model/build/{{clustername}}/private_dns.yaml
     regexp: '^    - ossec_client'
     line: '    # - ossec_client'


- name: Running public_dns playbook
  command: ansible-playbook -i hosts public_dns.yaml
  #environment: "{{proxy_env}}"
  register: out
  args: 
    chdir: systems-model/build/{{clustername}}/
- debug: 
    var: out


- name: Running private_dns playbook
  command: ansible-playbook -i hosts private_dns.yaml
  #environment: "{{proxy_env}}"
  register: out
  args: 
    chdir: systems-model/build/{{clustername}}/
- debug: 
     var: out


