
 - name: commenting  ossec-client in ossec-server
   replace: 
      path: systems-model/build/{{clustername}}/ossec_server.yaml
      regexp: '^    - ossec_client'
      replace: '    # - ossec_client'
 
 - name: Uncommenting rsnapshot-client in ossec-server 
   replace: 
      path: systems-model/build/{{clustername}}/ossec_server.yaml
      regexp: '^    # - rsnapshot_client'
      replace: '    - rsnapshot_client'
 
 - name: commenting ossec-client in config-server
   replace: 
      path: systems-model/build/{{clustername}}/config_server.yaml
      regexp: '^    - ossec_client'
      replace: '    # - ossec_client'
 
 - name: Uncommenting rsnapshot-client in config-server 
   replace: 
      path: systems-model/build/{{clustername}}/config_server.yaml
      regexp: '^    # - rsnapshot_client'
      replace: '    - rsnapshot_client'

 
 - name: commenting oseec-client in nagios-server
   replace: 
      path: systems-model/build/{{clustername}}/nagios_server.yaml
      regexp: '^    - ossec_client'
      replace: '    # - ossec_client'
 
 - name: Uncommenting rsnapshot-client in nagios-server
   replace: 
      path: systems-model/build/{{clustername}}/nagios_server.yaml
      regexp: '^    # - rsnapshot_client'
      replace: '    - rsnapshot_client'


 - name: commenting oseec-client in public-dns-server
   replace: 
      path: systems-model/build/{{clustername}}/public_dns.yaml
      regexp: '^    - ossec_client'
      replace: '    # - ossec_client'
 
 - name: Uncommenting rsnapshot-client in public-dns-server
   replace: 
      path: systems-model/build/{{clustername}}/public_dns.yaml
      regexp: '^    # - rsnapshot_client'
      replace: '    - rsnapshot_client'

 - name: commenting oseec-client in reverseproxy-server
   replace: 
      path: systems-model/build/{{clustername}}/reverseproxy_server.yaml
      regexp: '^    - ossec_client'
      replace: '    # - ossec_client'
 
 - name: Uncommenting rsnapshot-client in reverseproxy-server
   replace: 
      path: systems-model/build/{{clustername}}/reverseproxy_server.yaml
      regexp: '^    # - rsnapshot_client'
      replace: '    - rsnapshot_client'


 - name: commenting oseec-client in router
   replace: 
      path: systems-model/build/{{clustername}}/router.yaml
      regexp: '^    - ossec_client'
      replace: '    # - ossec_client'
 
 - name: Uncommenting rsnapshot-client in router
   replace: 
      path: systems-model/build/{{clustername}}/router.yaml
      regexp: '^    # - rsnapshot_client'
      replace: '    - rsnapshot_client'


 - name: commenting oseec-client in private-dns-server
   replace: 
      path: systems-model/build/{{clustername}}/private_dns.yaml
      regexp: '^    - ossec_client'
      replace: '    # - ossec_client'
 
 - name: Uncommenting rsnapshot-client in private-dns-server
   replace: 
      path: systems-model/build/{{clustername}}/private_dns.yaml
      regexp: '^    # - rsnapshot_client'
      replace: '    - rsnapshot_client'


 - name: commenting oseec-client in rsnapshot-server
   replace: 
      path: systems-model/build/{{clustername}}/rsnapshot_server.yaml
      regexp: '^    - ossec_client'
      replace: '    # - ossec_client'
 
 - name: Uncommenting rsnapshot-client in rsnapshot-server
   replace: 
      path: systems-model/build/{{clustername}}/rsnapshot_server.yaml
      regexp: '^    # - rsnapshot_client'
      replace: '    - rsnapshot_client'


 - name: commenting oseec-client in rsyslog-server
   replace: 
      path: systems-model/build/{{clustername}}/rsyslog_server.yaml
      regexp: '^    - ossec_client'
      replace: '    # - ossec_client'
 
 - name: Uncommenting rsnapshot-client in rsyslog-server
   replace: 
      path: systems-model/build/{{clustername}}/rsyslog_server.yaml
      regexp: '^    # - rsnapshot_client'
      replace: '    - rsnapshot_client'
