
- name: Testing  site yml file using ansible
  command: ansible-playbook -i hosts --list-tasks --syntax-check site.yaml
  register: out
  args:
     chdir: systems-model/build/{{clustername}}/
- debug: var=out.stdout_lines



- name: Running site yml file using ansible
  command: ansible-playbook -i hosts  site.yaml
  register: out
  args:
     chdir: systems-model/build/{{clustername}}/
- debug: var=out.stdout_lines
