---
- name: Set root password
  command: vzctl set 1010 --userpasswd root:{{vlead_user_password}}

- name: copy interface ifcfg-eth1 file
  copy: src=ifcfg-eth1 dest=/vz/private/1010/etc/sysconfig/network-scripts/

- name:  Network restart
  command: vzctl exec 1010 service network restart
# tasks file for Rsnapshot
