---
- name: Set root password
  command: vzctl set 1006 --userpasswd root:{{vlead_user_password}}

- name: copy interface ifcfg-eth1 file
  copy: src=ifcfg-eth1 dest=/vz/private/1006/etc/sysconfig/network-scripts/

- name: Public-dns-server Network restart
  command: vzctl exec 1006 service network restart
