---

    - replace: 
          path: roles/openvz/files/setup-ovpl-centos/scripts/config.sh
          regexp: 'export http_proxy=""'
          replace: 'export http_proxy="{{proxy_env.http_proxy}}"'
     
    - replace: 
          path: roles/openvz/files/setup-ovpl-centos/scripts/config.sh
          regexp: 'export https_proxy=""'
          replace: 'export https_proxy="{{proxy_env.https_proxy}}"'


    
    - name: running shell command
      command: ./centos_prepare_ovpl.sh
      register: out 
      args: 
        chdir: roles/openvz/files/setup-ovpl-centos/scripts/
    - debug: var=out.stdout_lines
