---
 - name: installing ansible and other required packages
   yum: name="{{item}}" state=latest
   environment: "{{proxy_env}}"
   with_items:
        - epel-release
        - ansible
        - git
        - emacs
 - name: Create vlead user and generate ssh-keys for vlead
   user: name=vlead password={{vlead_user_password}} generate_ssh_key=yes groups=wheel
 - name: Replacing wheel
   lineinfile: 
       path: /etc/sudoers 
       regexp: '^%wheel.*NOPASSWD: ALL.*'  
       line: '%wheel        ALL=(ALL)       NOPASSWD: ALL' 
       state: present
 - name: Set StrictHostkeyChecking to no
   lineinfile: path=/etc/ssh/ssh_config regexp="^Strict.*" line="StrictHostKeyChecking no" state=present
   notify: restart_ssh
 - name: Set PermitRootLogin to yes
   lineinfile: path=/etc/ssh/sshd_config regexp="^PermitRoot.*" line="PermitRootLogin yes" state=present
   notify: restart_ssh

 - name: Set PermitRootLogin to yes
   lineinfile: path=/etc/ssh/sshd_config regexp="^PasswordAuthentication.*" line="PasswordAuthentication yes" state=present
   notify: restart_ssh

 - name: Copy system-model repo from host-machine to ansible/config-serer container 
   synchronize: src="{{systems_model_dest}}" dest=/home/vlead/ 

 - name: Update ownership permissions to systems-model repo
   file: path=/home/vlead/systems-model recurse=true owner=vlead group=vlead 

