---
- name: Installing epel-release package
  yum: name=epel-release state=installed
  environment: "{{proxy_env}}"

- name: Installing rootkit hunter 
  yum: name=rkhunter state=latest
  environment: "{{proxy_env}}"

- name: Updating Dataabase of rkhunter
  command: rkhunter --update
  environment: "{{proxy_env}}"

- name: Updating system file properites
  command: rkhunter --propupd

- name: E-mail
  replace:
     path: /etc/rkhunter.conf
     regexp: '^#MAIL-ON-WARNING.*'
     replace: 'MAIL-ON-WARNING="shankar@vlabs.ac.in"'

- name: Replacing
  replace:
     path: /etc/rkhunter.conf
     regexp: '^ALLOW_SSH_ROOT_USER.*'
     replace: 'ALLOW_SSH_ROOT_USER=no'
